FROM python:3.10

WORKDIR /app

ADD ./requirements.txt app/requirements.txt

RUN pip install -r app/requirements.txt

RUN apt-get update && apt-get install libgl1 -y

ADD . /app

EXPOSE 8501

ENTRYPOINT [ "streamlit", "run" ]

CMD ["app.py"]
