FROM python:3.10

WORKDIR /app

ADD ./requirements.txt app/requirements.txt

RUN pip install -r app/requirements.txt

ADD . /app

EXPOSE 8000

# CMD uvicron fastApi:app --host $API_IP --port $API_PORT --reload
CMD ["uvicorn", "fastApi:app", "--host", "0.0.0.0", "--port", "8000", ]
# CMD ["uvicorn", "fastApi:app", "--host", "echo $API_IP", "--port", "8000", "--reload"]